package metrics

import (
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// WithRequestId is a replacement for https://github.com/gin-contrib/requestid.
//
// Unlike requestid, this middleware does not accept X-Request-ID header from incoming requests. It does set
// X-Request-ID on the response writer, and it makes the request available via RequestId instead of via gin.Context.
//
// The newly generated request Id (by way of uuid.NewString()) will be attached to the child slog.Logger retrievable via
// Slog. If you use a different logger, you'll want to write your own middleware instead.
//
// At the moment of writing, the middleware cannot be customised further.
func WithRequestId() func(cfg *LoggerConfig) {
	return func(cfg *LoggerConfig) {
		cfg.requestId = uuid.NewString
	}
}

const requestIdKey = "nguyengg/gin-metrics/requestIdKey"

// RequestId returns the request id that was generated by WithRequestId.
func RequestId(c *gin.Context) string {
	return c.GetString(requestIdKey)
}
