package ddb

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal/untyped"
)

// Put is a wrapper around [mapper.Mapper.Put].
//
// The item argument must be parseable by [mapper.New], and must be a struct pointer since the struct's fields may be
// modified on success.
//
// [DefaultClientProvider] is used to retrieve the DynamoDB client to make the service calls.
func Put(ctx context.Context, item any, optFns ...func(opts *PutOptions)) (*dynamodb.PutItemOutput, error) {
	client, err := DefaultClientProvider.Provide(ctx)
	if err != nil {
		return nil, err
	}

	m, err := untyped.NewFromItem(item, func(opts *untyped.Options) { opts.Client = client })
	if err != nil {
		return nil, err
	}

	return m.Put(ctx, item, internal.ApplyOpts(&PutOptions{}, optFns...).CopyTo)
}

// PutOptions customises [Put].
//
// PutOptions can be modified either by changing the fields directly or via chaining With methods.
type PutOptions struct {
	// DisableOptimisticLocking, if true, will disable optimistic locking functionality.
	DisableOptimisticLocking bool
	// DisableAutoGeneratedTimestamps, if true, will disable timestamp functionality.
	DisableAutoGeneratedTimestamps bool

	tableName *string
	condition expression.ConditionBuilder
	inputFn   func(input *dynamodb.PutItemInput)
	optFns    []func(opts *dynamodb.Options)
}

func (opts *PutOptions) CopyTo(untypedOpts *untyped.PutOptions) {
	untypedOpts.DisableOptimisticLocking = opts.DisableOptimisticLocking
	untypedOpts.DisableAutoGeneratedTimestamps = opts.DisableAutoGeneratedTimestamps
	untypedOpts.TableName = opts.tableName
	untypedOpts.Condition = opts.condition
	untypedOpts.InputFn = opts.inputFn
	untypedOpts.OptFns = opts.optFns
}

// WithTableNameOverride overrides the table name.
func (opts *PutOptions) WithTableNameOverride(tableName string) *PutOptions {
	opts.tableName = &tableName
	return opts
}

// WithInputOptions modifies the [dynamodb.PutItemInput] parameters right before invoking DynamoDB.
//
// Don't use WithInputOptions to modify [dynamodb.PutItemInput.ConditionExpression],
// [dynamodb.PutItemInput.ExpressionAttributeNames], and/or [dynamodb.PutItemInput.ExpressionAttributeNames] since they
// are most likely already filled out by the time fn runs. Instead, use And and Or which are designed to work in tandem
// therewith.
func (opts *PutOptions) WithInputOptions(fn func(input *dynamodb.PutItemInput)) *PutOptions {
	opts.inputFn = fn
	return opts
}

// WithClientOptions attaches options to the [dynamodb.Client.PutItem] invocation.
func (opts *PutOptions) WithClientOptions(optFns ...func(opts *dynamodb.Options)) *PutOptions {
	opts.optFns = optFns
	return opts
}

// And adds an [expression.And] to the [condition expression].
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *PutOptions) And(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *PutOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.And(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.And(other[0])
	default:
		opts.condition = right.And(other[0], other[1:]...)
	}
	return opts
}

// Or adds an [expression.Or] to the condition expression.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *PutOptions) Or(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *PutOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.Or(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.Or(other[0])
	default:
		opts.condition = right.Or(other[0], other[1:]...)
	}
	return opts
}
