package config

import (
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal/client"
)

// PutOptions customises a single [DynamoDB PutItem] call.
//
// PutOptions can be modified either by changing the fields directly or via chaining With methods.
//
// [DynamoDB PutItem]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html
type PutOptions struct {
	Config

	// DisableOptimisticLocking, if true, will disable optimistic locking functionality.
	DisableOptimisticLocking bool
	// DisableAutoGeneratedTimestamps, if true, will disable timestamp functionality.
	DisableAutoGeneratedTimestamps bool

	tableName *string
	condition expression.ConditionBuilder
	inputFn   func(input *dynamodb.PutItemInput)
	optFns    []func(opts *dynamodb.Options)
}

// WithTableNameOverride overrides the table name.
func (opts *PutOptions) WithTableNameOverride(tableName string) *PutOptions {
	opts.tableName = &tableName
	return opts
}

// WithInputOptions modifies the [dynamodb.PutItemInput] parameters right before invoking DynamoDB.
//
// Don't use WithInputOptions to modify [dynamodb.PutItemInput.ConditionExpression],
// [dynamodb.PutItemInput.ExpressionAttributeNames], and/or [dynamodb.PutItemInput.ExpressionAttributeNames] since they
// are most likely already filled out by the time fn runs. Instead, use And and Or which are designed to work in tandem
// therewith.
func (opts *PutOptions) WithInputOptions(fn func(input *dynamodb.PutItemInput)) *PutOptions {
	opts.inputFn = fn
	return opts
}

// WithClientOptions attaches options to the [dynamodb.Client.PutItem] invocation.
func (opts *PutOptions) WithClientOptions(optFns ...func(opts *dynamodb.Options)) *PutOptions {
	opts.optFns = optFns
	return opts
}

// And adds an [expression.And] to the [condition expression].
//
// Note that version condition will always be AND with conditions set by [PutOptions.And] and [PutOptions.Or] so that
// it can't be accidentally bypassed.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *PutOptions) And(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *PutOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.And(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.And(other[0])
	default:
		opts.condition = right.And(other[0], other[1:]...)
	}
	return opts
}

// Or adds an [expression.Or] to the [condition expression].
//
// Note that version condition will always be AND with conditions set by [PutOptions.And] and [PutOptions.Or] so that
// it can't be accidentally bypassed.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *PutOptions) Or(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *PutOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.Or(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.Or(other[0])
	default:
		opts.condition = right.Or(other[0], other[1:]...)
	}
	return opts
}

// Resolve creates the internal [client.ItemPutter].
func (opts *PutOptions) Resolve() *client.ItemPutter {
	return &client.ItemPutter{
		Config: client.Config{
			Client:         opts.Client,
			Encoder:        opts.Encoder,
			Decoder:        opts.Decoder,
			VersionUpdater: opts.VersionUpdater,
		},
		DisableOptimisticLocking:       opts.DisableOptimisticLocking,
		DisableAutoGeneratedTimestamps: opts.DisableAutoGeneratedTimestamps,
		TableNameOverride:              opts.tableName,
		Condition:                      opts.condition,
		InputFn:                        opts.inputFn,
		OptFns:                         opts.optFns,
	}
}
