package config

import (
	"fmt"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal/client"
	ddbtypes "github.com/nguyengg/go-aws-commons/ddb-mapper/types"
)

// UpdateOptions customises a single [DynamoDB UpdateItem] call.
//
// UpdateOptions can be modified either by changing the fields directly or via chaining With methods.
//
// The update methods ([UpdateOptions.Set], [UpdateOptions.Remove], [UpdateOptions.Add], and [UpdateOptions.Delete]) all
// require a path argument that must be either a string (which will be wrapped using [expression.Name]), or an
// [expression.NameBuilder] so that you can use [expression.NameNoDotSplit]. For update methods that require a value
// argument, the value will be wrapped with [expression.Value] if not already one so you can use
// [expression.ValueWithOptions] if the need arises.
//
// [DynamoDB UpdateItem]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html
type UpdateOptions struct {
	Config

	// DisableOptimisticLocking, if true, will disable optimistic locking functionality.
	DisableOptimisticLocking bool
	// DisableAutoGeneratedTimestamps, if true, will disable timestamp functionality.
	DisableAutoGeneratedTimestamps bool

	tableName            *string
	updateBehaviour      ddbtypes.UpdateBehaviour
	updateBehaviourIsSet bool
	update               expression.UpdateBuilder
	updateIsSet          bool
	condition            expression.ConditionBuilder
	returnAllNewValues   bool
	inputFn              func(input *dynamodb.UpdateItemInput)
	optFns               []func(opts *dynamodb.Options)
}

// WithTableNameOverride overrides the table name.
func (opts *UpdateOptions) WithTableNameOverride(tableName string) *UpdateOptions {
	opts.tableName = &tableName
	return opts
}

// WithInputOptions modifies the [dynamodb.UpdateItemInput] parameters right before invoking DynamoDB.
//
// Don't use WithInputOptions to modify [dynamodb.UpdateItemInput.ConditionExpression],
// [dynamodb.UpdateItemInput.UpdateExpression], [dynamodb.UpdateItemInput.ExpressionAttributeNames], and/or
// [dynamodb.UpdateItemInput.ExpressionAttributeNames] since they are most likely already filled out by the time fn
// runs. Instead, use And and Or which are designed to work in tandem therewith.
func (opts *UpdateOptions) WithInputOptions(fn func(input *dynamodb.UpdateItemInput)) *UpdateOptions {
	opts.inputFn = fn
	return opts
}

// WithClientOptions attaches options to the [dynamodb.Client.UpdateItem] invocation.
func (opts *UpdateOptions) WithClientOptions(optFns ...func(opts *dynamodb.Options)) *UpdateOptions {
	opts.optFns = optFns
	return opts
}

// And adds an [expression.And] to the [condition expression].
//
// Note that version condition will always be AND with conditions set by [UpdateOptions.And] and [UpdateOptions.Or] so
// that it can't be accidentally bypassed.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *UpdateOptions) And(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *UpdateOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.And(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.And(other[0])
	default:
		opts.condition = right.And(other[0], other[1:]...)
	}
	return opts
}

// Or adds an [expression.Or] to the condition expression.
//
// Note that version condition will always be AND with conditions set by [UpdateOptions.And] and [UpdateOptions.Or] so
// that it can't be accidentally bypassed.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *UpdateOptions) Or(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *UpdateOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.Or(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.Or(other[0])
	default:
		opts.condition = right.Or(other[0], other[1:]...)
	}
	return opts
}

// nb panics if a is neither string nor expression.NameBuilder.
func nb(a any) expression.NameBuilder {
	switch v := a.(type) {
	case string:
		return expression.Name(v)
	case expression.NameBuilder:
		return v
	case *expression.NameBuilder:
		return *v
	default:
		// sorry but I'm not going to check for **expression.NameBuilder.
		panic(fmt.Errorf("expected string or %s, got %T instead", reflect.TypeFor[expression.NameBuilder](), a))
	}
}

// vb wraps a in expression.Value if it is not already an expression.ValueBuilder.
func vb(a any) expression.ValueBuilder {
	if v, ok := a.(expression.ValueBuilder); ok {
		return v
	}

	return expression.Value(a)
}

// ob wraps a in expression.Value if it is not already an expression.OperandBuilder.
func ob(a any) expression.OperandBuilder {
	if v, ok := a.(expression.OperandBuilder); ok {
		return v
	}

	return expression.Value(a)
}

// Add adds an ["ADD path value" clause] to the update expression for updating a number or adding elements to a set.
//
// When [adding to a set], you will want the value argument to be either [types.AttributeValueMemberSS],
// [types.AttributeValueMemberNS], or [types.AttributeValueMemberBS] accordingly. Panics if path is not a string or
// pre-wrapped as [expression.NameBuilder].
//
// [adding to a set]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD.Set
// ["ADD path value" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD
func (opts *UpdateOptions) Add(path, value any) *UpdateOptions {
	opts.update = opts.update.Add(nb(path), vb(value))

	return opts
}

// Delete adds a ["DELETE path subset" clause] to the update expression to remove on or more elements from a set.
//
// You will want the value argument to be either [types.AttributeValueMemberSS], [types.AttributeValueMemberNS], or
// [types.AttributeValueMemberBS] accordingly. Panics if path is not a string or pre-wrapped as
// [expression.NameBuilder].
//
// ["DELETE path subset" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.DELETE
func (opts *UpdateOptions) Delete(path, subset any) *UpdateOptions {
	opts.update = opts.update.Delete(nb(path), vb(subset))

	return opts
}

// Set adds a ["SET path = value" clause] to the update expression to add or overwrite the named attribute.
//
// The value argument is wrapped with [expression.Value] if it is not already an [expression.OperandBuilder]; for
// example, you can use [expression.IfNotExists] to prevent overwriting an attribute. Panics if path is not a string or
// pre-wrapped as [expression.NameBuilder].
//
// ["SET path = value" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET
func (opts *UpdateOptions) Set(path, value any) *UpdateOptions {
	opts.update = opts.update.Set(nb(path), ob(value))

	return opts
}

// Remove adds a ["REMOVE path" clause] to the update expression to delete the attribute identified by path.
//
// Panics if path is not a string or pre-wrapped as [expression.NameBuilder].
//
// ["REMOVE path" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.REMOVE
func (opts *UpdateOptions) Remove(path any) *UpdateOptions {
	opts.update = opts.update.Remove(nb(path))

	return opts
}

// SetOrRemove adds either [UpdateOptions.Set] or [UpdateOptions.Remove] action to the update expression.
//
// If set is true, a SET action will be added.
// If set is false, only when remove is true then a REMOVE action will be added.
//
// | set   | remove | action
// | true  | *      | SET
// | false | true   | REMOVE
// | false | false  | no-op
//
// This is useful for distinguishing between PUT/POST (remove=true) that replaces attributes with clobbering behaviour
// vs. PATCH (remove=false) that will only update attributes that are non-nil. For example:
//
//	func PUT(body Request) {
//		// because it's a PUT request, if notes is empty, instead of writing empty string to database, we'll remove it.
//		opts.SetOrRemove(true, true, "notes", body.Notes)
//	}
//
//	func PATCH(body Request) {
//		// only when notes is non-empty that we'll update it. an empty notes just means caller didn't try to update it.
//		opts.SetOrRemove(body.Notes != "", false, "notes", body.Notes
//	}
//
//	func CreateUpdateItem(method string, body Request) {
//		// an attempt to unify the methods may look like this.
//		opts.SetOrRemove(body.Notes != "", method != "PATCH", "notes", body.Notes)
//	}
//
// The value argument is wrapped with [expression.Value] if it is not already an [expression.OperandBuilder]; for
// example, you can use [expression.IfNotExists] to prevent overwriting an attribute. Panics if path is not a string or
// pre-wrapped as [expression.NameBuilder].
func (opts *UpdateOptions) SetOrRemove(set, remove bool, path, value any) *UpdateOptions {
	if set {
		opts.update = opts.update.Set(nb(path), ob(value))
		return opts
	}

	if remove {
		opts.update = opts.update.Remove(nb(path))
	}

	return opts
}

// SetOrRemoveStringPointer is a specialization of [UpdateOptions.SetOrRemove] for string pointer value.
//
// If ptr is a nil pointer, no action is taken. If ptr dereferences to an empty string, a REMOVE action is used.
// A non-empty string otherwise will result in a SET action. Panics if path is not a string or pre-wrapped as
// [expression.NameBuilder].
//
// Usage:
//
//	type Request struct {
//		Description *string `json:"description"`
//	}
//
//	func PATCH(body Request) {
//		// { "description": "" } would remove the "description" attribute from the item.
//		// { "description": "some description" } would set the "description" attribute to value "some description".
//		// { "description": null } or the "description" field is missing would do no-op.
//		opts.SetOrRemoveStringPointer("description", body.Description)
//	}
func (opts *UpdateOptions) SetOrRemoveStringPointer(path any, ptr *string) *UpdateOptions {
	if ptr == nil {
		return opts
	}

	if v := *ptr; v != "" {
		opts.update = opts.update.Set(nb(path), expression.Value(v))
		return opts
	}

	opts.update = opts.update.Remove(nb(path))
	return opts
}

// WithUpdateBehaviour is inspired by [DynamoDBMapperConfig.SaveBehavior] to populate the update expression using the
// map[string]AttributeValue marshaled from the item.
//
// If the map[string]AttributeValue already omits a field due to usage of "omitempty", "stringset", etc., they will not
// be updated. All attributes otherwise will be updated using a SET clause.
//
// WithUpdateBehaviour is smart enough to not add overlapping SET clauses for version and timestamps. However, if you
// manually call [UpdateOptions.Set], [UpdateOptions.Remove], [UpdateOptions.Add], and/or [UpdateOptions.Delete], don't
// use WithUpdateBehaviour lest you risk
// "[Invalid UpdateExpression]: Two document paths overlap with each other; must remove or rewrite one of these paths".
//
// It is difficult to make UpdateOptions smarter by detecting which attributes have already been modified via the
// clauses created by UpdateOptions unless:
//  1. [expression.NameBuilder] exports its name slice or allows access otherwise.
//  2. UpdateOptions disallows passing [expression.NameBuilder] as path, and instead only allows string path arguments.
//
// [DynamoDBMapperConfig.SaveBehavior]: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.SaveBehavior.html
// [Invalid UpdateExpression]: https://repost.aws/questions/QUlkAub4uRTd20goMIx4XGvg
func (opts *UpdateOptions) WithUpdateBehaviour(flag ddbtypes.UpdateBehaviour) *UpdateOptions {
	opts.updateBehaviour = flag
	opts.updateBehaviourIsSet = true
	return opts
}

// Resolve creates the internal [client.ItemUpdater].
func (opts *UpdateOptions) Resolve() *client.ItemUpdater {
	return &client.ItemUpdater{
		Config: client.Config{
			Client:         opts.Client,
			Encoder:        opts.Encoder,
			Decoder:        opts.Decoder,
			VersionUpdater: opts.VersionUpdater,
		},
		DisableOptimisticLocking:       opts.DisableOptimisticLocking,
		DisableAutoGeneratedTimestamps: opts.DisableAutoGeneratedTimestamps,
		TableNameOverride:              opts.tableName,
		UpdateBehaviour:                opts.updateBehaviour,
		UpdateBehaviourIsSet:           opts.updateBehaviourIsSet,
		Update:                         opts.update,
		UpdateIsSet:                    opts.updateIsSet,
		Condition:                      opts.condition,
		ReturnAllNewValues:             opts.returnAllNewValues,
		InputFn:                        opts.inputFn,
		OptFns:                         opts.optFns,
	}
}

var _ types.AttributeValue
