package client

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/config"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/model"
	ddbtypes "github.com/nguyengg/go-aws-commons/ddb-mapper/types"
)

// ItemUpdater is the client for executing [DynamoDB UpdateItem].
//
// [DynamoDB UpdateItem]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html
type ItemUpdater struct {
	config.Config
	*model.TableModel // model MUST NOT be mutated.

	DisableOptimisticLocking       bool
	DisableAutoGeneratedTimestamps bool
	TableNameOverride              *string
	UpdateBehaviour                ddbtypes.UpdateBehaviour
	UpdateBehaviourIsSet           bool
	Update                         expression.UpdateBuilder
	UpdateIsSet                    bool
	Condition                      expression.ConditionBuilder
	ReturnAllNewValues             bool
	InputFn                        func(input *dynamodb.UpdateItemInput)
	OptFns                         []func(opts *dynamodb.Options)
}

func (c *ItemUpdater) Execute(ctx context.Context, item any) (updateItemOutput *dynamodb.UpdateItemOutput, err error) {
	if err = initConfig(ctx, &c.Config); err != nil {
		return nil, err
	}

	v, ptr, err := internal.IndirectValueIsStruct(item, true, c.StructType)
	if err != nil {
		return nil, err
	}

	reset := internal.Chainable()
	if !c.DisableOptimisticLocking && c.Version != nil {
		undo, cond, err := updateVersion(c.TableModel, v, ptr, c.VersionUpdater)
		if err != nil {
			return nil, err
		} else if c.Condition.IsSet() {
			c.Condition = c.Condition.And(cond)
		} else {
			c.Condition = cond
		}
		reset = reset.And(undo)
	}

	if !c.DisableAutoGeneratedTimestamps && c.ModifiedTime != nil {
		reset = reset.And(updateTimestamps(c.TableModel, v, time.Now(), false))
	}

	// instead of marshaling just the key, we'll marshal the entire item here so that we can use the AttributeValue
	// from the map's version and timestamps mappings to add to update expression.
	avM, err := c.Encode(item, c.CopyTo)
	if err != nil {
		return nil, err
	}

	if !c.DisableOptimisticLocking && c.Version != nil {
		if v, ok := avM[c.Version.AttrName]; ok {
			c.Update = c.Update.Set(expression.NameNoDotSplit(c.Version.AttrName), expression.Value(v))
		}
	}

	if !c.DisableAutoGeneratedTimestamps && c.ModifiedTime != nil {
		if v, ok := avM[c.ModifiedTime.AttrName]; ok {
			c.Update = c.Update.Set(expression.NameNoDotSplit(c.ModifiedTime.AttrName), expression.Value(v))
		}
	}

	if c.UpdateBehaviourIsSet {
		for n, av := range avM {
			attr, ok := c.Others[n]
			if !ok {
				// this will skip special attributes except for createdTime which is not set by Update.
				if c.CreatedTime != nil && n == c.CreatedTime.AttrName {
					attr = *c.CreatedTime
				} else {
					continue
				}
			}

			if c.UpdateBehaviour&ddbtypes.UpdateBehaviourSkipZeroValues != 0 {
				if v.FieldByIndex(attr.Index).IsZero() {
					continue
				}
			}

			if _, isNull := av.(*types.AttributeValueMemberNULL); isNull {
				switch {
				case c.UpdateBehaviour&ddbtypes.UpdateBehaviourSkipNULLDataType != 0:
					continue
				case c.UpdateBehaviour&ddbtypes.UpdateBehaviourRemoveNULLDataType != 0:
					c.Update = c.Update.Remove(expression.NameNoDotSplit(n))
					continue
				}
			}

			c.Update = c.Update.Set(expression.NameNoDotSplit(n), expression.Value(av))
		}
	}

	b := expression.NewBuilder().WithUpdate(c.Update)
	if c.Condition.IsSet() {
		b = b.WithCondition(c.Condition)
	}

	expr, err := b.Build()
	if err != nil {
		if strings.Contains(err.Error(), "unset parameter: UpdateBuilder") {
			return nil, fmt.Errorf("build expressions error (did you forget to add an update clause?): %w", err)
		}

		return nil, fmt.Errorf("build expressions error: %w", err)
	}

	input := &dynamodb.UpdateItemInput{TableName: aws.String(c.TableName)}

	// since we have the full item map[string]AttributeValue, copy it into Key and keep only the keys.
	if input.Key = map[string]types.AttributeValue{c.HashKey.AttrName: avM[c.HashKey.AttrName]}; c.SortKey != nil {
		input.Key[c.SortKey.AttrName] = avM[c.SortKey.AttrName]
	}
	input.UpdateExpression = expr.Update()
	input.ConditionExpression = expr.Condition()
	input.ExpressionAttributeNames = expr.Names()
	input.ExpressionAttributeValues = expr.Values()

	if c.TableNameOverride != nil {
		input.TableName = c.TableNameOverride
	}
	if c.ReturnAllNewValues && input.ReturnValues == "" {
		input.ReturnValues = types.ReturnValueAllNew
	}
	if c.InputFn != nil {
		c.InputFn(input)
	}

	if updateItemOutput, err = c.Client.UpdateItem(ctx, input, c.OptFns...); err != nil {
		reset()
		err = fmt.Errorf("dynamodb UpdateItem error: %w", err)
		return
	}

	if c.ReturnAllNewValues && input.ReturnValues == types.ReturnValueAllNew {
		if attributes := updateItemOutput.Attributes; len(attributes) != 0 {
			v.Set(reflect.Zero(c.StructType))

			if err = c.Decoder.Decode(&types.AttributeValueMemberM{Value: attributes}, ptr.Interface()); err != nil {
				return nil, fmt.Errorf("unmarshal ALL_NEW attributes to type %T error: %w", item, err)
			}
		}
	}

	return updateItemOutput, nil
}
