package mapper

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal/untyped"
)

// Put uses [DynamoDB PutItem] to create a new item, or replace an old item with a new item.
//
// [DynamoDB PutItem] uses clobbering behaviour: the item argument is marshaled with [Options.Encoder] to produce the
// [dynamodb.PutItemInput.Item] that completely replaces or adds a new item in DynamoDB. As a result, Mapper.Put differs
// from [Mapper.Update] on how optimistic locking and timestamp generations work while preparing for the
// [dynamodb.Client.PutItem] call:
//   - The item's version will be updated to the next value using [Options.NextVersion]. If the original version is the
//     zero value, `attribute_not_exists(#hashkey)` is the [condition expression] to prevent overwriting an existing
//     item; otherwise, `#version = :version` is used. This logic can be disabled with
//     [PutOptions.DisableOptimisticLocking].
//   - The item's created time is only updated when the original value is the zero value; its modified time is always
//     updated to [time.Now].
//
// Any non-nil error will restore the item argument to its original state.
//
// [DynamoDB PutItem]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (m *Mapper[T]) Put(ctx context.Context, item *T, optFns ...func(opts *PutOptions)) (*dynamodb.PutItemOutput, error) {
	return m.Mapper.Put(ctx, item, internal.ApplyOpts(&PutOptions{}, optFns...).CopyTo)
}

// PutOptions customises [Put].
//
// PutOptions can be modified either by changing the fields directly or via chaining With methods.
type PutOptions struct {
	// DisableOptimisticLocking, if true, will disable optimistic locking functionality.
	DisableOptimisticLocking bool
	// DisableAutoGeneratedTimestamps, if true, will disable timestamp functionality.
	DisableAutoGeneratedTimestamps bool

	tableName *string
	condition expression.ConditionBuilder
	inputFn   func(input *dynamodb.PutItemInput)
	optFns    []func(opts *dynamodb.Options)
}

func (opts *PutOptions) CopyTo(untypedOpts *untyped.PutOptions) {
	untypedOpts.DisableOptimisticLocking = opts.DisableOptimisticLocking
	untypedOpts.DisableAutoGeneratedTimestamps = opts.DisableAutoGeneratedTimestamps
	untypedOpts.TableName = opts.tableName
	untypedOpts.Condition = opts.condition
	untypedOpts.InputFn = opts.inputFn
	untypedOpts.OptFns = opts.optFns
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Common options.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// WithTableNameOverride overrides the table name.
func (opts *PutOptions) WithTableNameOverride(tableName string) *PutOptions {
	opts.tableName = &tableName
	return opts
}

// WithInputOptions modifies the [dynamodb.PutItemInput] parameters right before invoking DynamoDB.
//
// Don't use WithInputOptions to modify [dynamodb.PutItemInput.ConditionExpression],
// [dynamodb.PutItemInput.ExpressionAttributeNames], and/or [dynamodb.PutItemInput.ExpressionAttributeNames] since they
// are most likely already filled out by the time fn runs. Instead, use And and Or which are designed to work in tandem
// therewith.
func (opts *PutOptions) WithInputOptions(fn func(input *dynamodb.PutItemInput)) *PutOptions {
	opts.inputFn = fn
	return opts
}

// WithClientOptions attaches options to the [dynamodb.Client.PutItem] invocation.
func (opts *PutOptions) WithClientOptions(optFns ...func(opts *dynamodb.Options)) *PutOptions {
	opts.optFns = optFns
	return opts
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Conditional options
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// And adds an [expression.And] to the [condition expression].
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *PutOptions) And(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *PutOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.And(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.And(other[0])
	default:
		opts.condition = right.And(other[0], other[1:]...)
	}
	return opts
}

// Or adds an [expression.Or] to the condition expression.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *PutOptions) Or(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *PutOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.Or(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.Or(other[0])
	default:
		opts.condition = right.Or(other[0], other[1:]...)
	}
	return opts
}
