package mapper

import (
	"context"
	"fmt"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal/untyped"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/types"
)

// Update uses [DynamoDB UpdateItem] to edit an existing item's attributes, or adds a new item if it does not already
// exist.
//
// Because [DynamoDB UpdateItem] only requires the key of the item ([dynamodb.UpdateItemInput.Key]) while the
// [update expression] ([dynamodb.UpdateItemOutput.UpdateExpression]) effects changes to the item's attributes, you will
// // want to use optFns to add at least one update clause. Use [UpdateOptions.Set], [UpdateOptions.Remove],
// [UpdateOptions.Add], [UpdateOptions.Delete], and/or [UpdateOptions.WithUpdateBehaviour] to do so. For the same
// reason, Mapper.Update differs from [Mapper.Put] on how optimistic locking and timestamps generation work while
// preparing for the [dynamodb.Client.UpdateItem] call:
//   - The item's version will be updated to the next value using [Config.NextVersion]. If the original version is the
//     zero value, `attribute_not_exists(#hashkey)` is the [condition expression] to prevent overwriting an existing
//     item; otherwise, `#version = :version` is used. A `SET #version :version` clause is added to the update
//     expression. This logic can be disabled with [PutOptions.DisableOptimisticLocking], especially if you're going to
//     manually update the version.
//   - The item's modified time attribute is always updated to [time.Now]; its created time is untouched. A
//     `SET #modifiedTime :now` clause is added to the update expression. If Mapper.Update is being used to create a new
//     item, you may want to manually set the same created time and modified time, and disable timestamp generation with
//     [UpdateOptions.DisableAutoGeneratedTimestamps].
//
// [DynamoDB UpdateItem]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html
// [update expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (m *Mapper[T]) Update(ctx context.Context, item *T, optFns ...func(opts *UpdateOptions)) (*dynamodb.UpdateItemOutput, error) {
	return m.Mapper.Update(ctx, item, internal.ApplyOpts(&UpdateOptions{}, optFns...).CopyTo)
}

// UpdateOptions customises [Update].
//
// UpdateOptions can be modified either by changing the fields directly or via chaining With methods.
//
// The update methods (Set, Remove, Add, and Delete) all require a path argument that must be either a string (which
// will be wrapped using [expression.Name]), or an [expression.NameBuilder] so that you can use
// [expression.NameNoDotSplit] as the path. For update methods that require a value argument, the value will be wrapped
// with [expression.Value] if not already one so you can use [expression.ValueWithOptions] if the need arises.
type UpdateOptions struct {
	// DisableOptimisticLocking, if true, will disable optimistic locking functionality.
	DisableOptimisticLocking bool
	// DisableAutoGeneratedTimestamps, if true, will disable timestamp functionality.
	DisableAutoGeneratedTimestamps bool

	tableName            *string
	updateBehaviour      types.UpdateBehaviour
	updateBehaviourIsSet bool
	update               expression.UpdateBuilder
	updateIsSet          bool
	condition            expression.ConditionBuilder
	returnAllNewValues   bool
	inputFn              func(input *dynamodb.UpdateItemInput)
	optFns               []func(opts *dynamodb.Options)
}

func (opts *UpdateOptions) CopyTo(untypedOpts *untyped.UpdateOptions) {
	untypedOpts.DisableOptimisticLocking = opts.DisableOptimisticLocking
	untypedOpts.DisableAutoGeneratedTimestamps = opts.DisableAutoGeneratedTimestamps
	untypedOpts.TableName = opts.tableName
	untypedOpts.UpdateBehaviour = opts.updateBehaviour
	untypedOpts.UpdateBehaviourIsSet = opts.updateBehaviourIsSet
	untypedOpts.Update = opts.update
	untypedOpts.UpdateIsSet = opts.updateIsSet
	untypedOpts.Condition = opts.condition
	untypedOpts.ReturnAllNewValues = opts.returnAllNewValues
	untypedOpts.InputFn = opts.inputFn
	untypedOpts.OptFns = opts.optFns
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Common options.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// WithTableNameOverride overrides the table name.
func (opts *UpdateOptions) WithTableNameOverride(tableName string) *UpdateOptions {
	opts.tableName = &tableName
	return opts
}

// WithInputOptions modifies the [dynamodb.UpdateItemInput] parameters right before invoking DynamoDB.
//
// Don't use WithInputOptions to modify [dynamodb.UpdateItemInput.ConditionExpression],
// [dynamodb.UpdateItemInput.UpdateExpression], [dynamodb.UpdateItemInput.ExpressionAttributeNames], and/or
// [dynamodb.UpdateItemInput.ExpressionAttributeNames] since they are most likely already filled out by the time fn
// runs. Instead, use And and Or which are designed to work in tandem therewith.
func (opts *UpdateOptions) WithInputOptions(fn func(input *dynamodb.UpdateItemInput)) *UpdateOptions {
	opts.inputFn = fn
	return opts
}

// WithClientOptions attaches options to the [dynamodb.Client.UpdateItem] invocation.
func (opts *UpdateOptions) WithClientOptions(optFns ...func(opts *dynamodb.Options)) *UpdateOptions {
	opts.optFns = optFns
	return opts
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Conditional options
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// And adds an [expression.And] to the [condition expression].
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *UpdateOptions) And(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *UpdateOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.And(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.And(other[0])
	default:
		opts.condition = right.And(other[0], other[1:]...)
	}
	return opts
}

// Or adds an [expression.Or] to the condition expression.
//
// [condition expression]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
func (opts *UpdateOptions) Or(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *UpdateOptions {
	if opts.condition.IsSet() {
		opts.condition = opts.condition.Or(right, other...)
		return opts
	}

	switch len(other) {
	case 0:
		opts.condition = right
	case 1:
		opts.condition = right.Or(other[0])
	default:
		opts.condition = right.Or(other[0], other[1:]...)
	}
	return opts
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Update options
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// nb panics if a is neither string nor expression.NameBuilder.
func nb(a any) expression.NameBuilder {
	switch v := a.(type) {
	case string:
		return expression.Name(v)
	case expression.NameBuilder:
		return v
	case *expression.NameBuilder:
		return *v
	default:
		// sorry but I'm not going to check for **expression.NameBuilder.
		panic(fmt.Errorf("expected string or %s, got %T instead", reflect.TypeFor[expression.NameBuilder](), a))
	}
}

// vb wraps a in expression.Value if it is not already an expression.ValueBuilder.
func vb(a any) expression.ValueBuilder {
	if v, ok := a.(expression.ValueBuilder); ok {
		return v
	}

	return expression.Value(a)
}

// ob wraps a in expression.Value if it is not already an expression.OperandBuilder.
func ob(a any) expression.OperandBuilder {
	if v, ok := a.(expression.OperandBuilder); ok {
		return v
	}

	return expression.Value(a)
}

// Add adds an ["ADD path value" clause] to the update expression for updating a number or adding elements to a set.
//
// When [adding to a set], you will want the value argument to be either [types.AttributeValueMemberSS],
// [types.AttributeValueMemberNS], or [types.AttributeValueMemberBS] accordingly. Panics if path is not a string or
// pre-wrapped as [expression.NameBuilder].
//
// [adding to a set]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD.Set
// ["ADD path value" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD
func (opts *UpdateOptions) Add(path, value any) *UpdateOptions {
	opts.update = opts.update.Add(nb(path), vb(value))

	return opts
}

// Delete adds a ["DELETE path subset" clause] to the update expression to remove on or more elements from a set.
//
// You will want the value argument to be either [types.AttributeValueMemberSS], [types.AttributeValueMemberNS], or
// [types.AttributeValueMemberBS] accordingly. Panics if path is not a string or pre-wrapped as
// [expression.NameBuilder].
//
// ["DELETE path subset" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.DELETE
func (opts *UpdateOptions) Delete(path, subset any) *UpdateOptions {
	opts.update = opts.update.Delete(nb(path), vb(subset))

	return opts
}

// Set adds a ["SET path = value" clause] to the update expression to add or overwrite the named attribute.
//
// The value argument is wrapped with [expression.Value] if it is not already an [expression.OperandBuilder]; for
// example, you can use [expression.IfNotExists] to prevent overwriting an attribute. Panics if path is not a string or
// pre-wrapped as [expression.NameBuilder].
//
// ["SET path = value" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET
func (opts *UpdateOptions) Set(path, value any) *UpdateOptions {
	opts.update = opts.update.Set(nb(path), ob(value))

	return opts
}

// Remove adds a ["REMOVE path" clause] to the update expression to delete the attribute identified by path.
//
// Panics if path is not a string or pre-wrapped as [expression.NameBuilder].
//
// ["REMOVE path" clause]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.REMOVE
func (opts *UpdateOptions) Remove(path string) *UpdateOptions {
	opts.update = opts.update.Remove(nb(path))

	return opts
}

// SetOrRemove adds either Set or Remove action to the update expression.
//
// If set is true, a SET action will be added.
// If set is false, only when remove is true then a REMOVE action will be added.
//
// | set   | remove | action
// | true  | *      | SET
// | false | true   | REMOVE
// | false | false  | no-op
//
// This is useful for distinguishing between PUT/POST (remove=true) that replaces attributes with clobbering behaviour
// vs. PATCH (remove=false) that will only update attributes that are non-nil. For example:
//
//	func PUT(body Request) {
//		// because it's a PUT request, if notes is empty, instead of writing empty string to database, we'll remove it.
//		opts.SetOrRemove(true, true, "notes", body.Notes)
//	}
//
//	func PATCH(body Request) {
//		// only when notes is non-empty that we'll update it. an empty notes just means caller didn't try to update it.
//		opts.SetOrRemove(body.Notes != "", false, "notes", body.Notes
//	}
//
//	func CreateUpdateItem(method string, body Request) {
//		// an attempt to unify the methods may look like this.
//		opts.SetOrRemove(body.Notes != "", method != "PATCH", "notes", body.Notes)
//	}
//
// The value argument is wrapped with [expression.Value] if it is not already an [expression.OperandBuilder]; for
// example, you can use [expression.IfNotExists] to prevent overwriting an attribute. Panics if path is not a string or
// pre-wrapped as [expression.NameBuilder].
func (opts *UpdateOptions) SetOrRemove(set, remove bool, path, value any) *UpdateOptions {
	if set {
		opts.update = opts.update.Set(nb(path), ob(value))
		return opts
	}

	if remove {
		opts.update = opts.update.Remove(nb(path))
	}

	return opts
}

// SetOrRemoveStringPointer is a specialization of SetOrRemove for string pointer value.
//
// If ptr is a nil pointer, no action is taken. If ptr dereferences to an empty string, a REMOVE action is used.
// A non-empty string otherwise will result in a SET action. Panics if path is not a string or pre-wrapped as
// [expression.NameBuilder].
//
// Usage:
//
//	type Request struct {
//		Description *string `json:"description"`
//	}
//
//	func PATCH(body Request) {
//		// { "description": "" } would remove the "description" attribute from the item.
//		// { "description": "some description" } would set the "description" attribute to value "some description".
//		// { "description": null } or the "description" field is missing would do no-op.
//		opts.SetOrRemoveStringPointer("description", body.Description)
//	}
func (opts *UpdateOptions) SetOrRemoveStringPointer(path any, ptr *string) *UpdateOptions {
	if ptr == nil {
		return opts
	}

	if v := *ptr; v != "" {
		opts.update = opts.update.Set(nb(path), expression.Value(v))
		return opts
	}

	opts.update = opts.update.Remove(nb(path))
	return opts
}

// WithUpdateBehaviour is inspired by [DynamoDBMapperConfig.SaveBehavior] to populate the update expression using the
// map[string]AttributeValue marshaled from the item.
//
// If the map[string]AttributeValue already omits a field due to usage of "omitempty", "stringset", etc., they will not
// be updated. All attributes otherwise will be updated using a SET clause.
//
// WithUpdateBehaviour is smart enough to not add overlapping SET clauses for version and timestamps. However, if you
// manually call Set, Remove, Add, and Delete, don't use WithUpdateBehaviour lest you risk "[Invalid UpdateExpression]:
// Two document paths overlap with each other; must remove or rewrite one of these paths".
//
// [DynamoDBMapperConfig.SaveBehavior]: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.SaveBehavior.html
// [Invalid UpdateExpression]: https://repost.aws/questions/QUlkAub4uRTd20goMIx4XGvg
func (opts *UpdateOptions) WithUpdateBehaviour(flag types.UpdateBehaviour) *UpdateOptions {
	opts.updateBehaviour = flag
	opts.updateBehaviourIsSet = true
	return opts
}
