package untyped

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal"
)

func (m *Mapper) Put(ctx context.Context, item any, optFns ...func(opts *PutOptions)) (*dynamodb.PutItemOutput, error) {
	var (
		opts  = internal.ApplyOpts(&PutOptions{}, optFns...)
		reset = internal.Chainable()
	)

	c, err := Merge(ctx, m.Options, opts.Options)
	if err != nil {
		return nil, err
	}

	v, ptr, err := internal.IndirectValueIsStruct(item, true, m.StructType)
	if err != nil {
		return nil, err
	}

	if !opts.DisableOptimisticLocking && m.Version != nil {
		undo, cond := m.updateVersion(c, v, ptr)
		if opts.Condition.IsSet() {
			opts.Condition = opts.Condition.And(cond)
		} else {
			opts.Condition = cond
		}
		reset = reset.And(undo)
	}

	if !opts.DisableAutoGeneratedTimestamps {
		reset = reset.And(m.updateTimestamps(v, time.Now(), true))
	}

	input := &dynamodb.PutItemInput{TableName: aws.String(m.TableName)}
	if input.Item, err = m.encode(c, item); err != nil {
		return nil, err
	}

	if opts.Condition.IsSet() {
		expr, err := expression.NewBuilder().WithCondition(opts.Condition).Build()
		if err != nil {
			return nil, fmt.Errorf("build expressions error: %w", err)
		}

		input.ConditionExpression = expr.Condition()
		input.ExpressionAttributeNames = expr.Names()
		input.ExpressionAttributeValues = expr.Values()
	}
	if opts.TableName != nil {
		input.TableName = opts.TableName
	}
	if opts.InputFn != nil {
		opts.InputFn(input)
	}

	putItemOutput, err := c.Client.PutItem(ctx, input, opts.OptFns...)
	if err != nil {
		reset()
		return putItemOutput, fmt.Errorf("dynamodb PutItem error: %w", err)
	}

	return putItemOutput, nil
}

type PutOptions struct {
	Options

	DisableOptimisticLocking       bool
	DisableAutoGeneratedTimestamps bool

	TableName *string
	Condition expression.ConditionBuilder
	InputFn   func(input *dynamodb.PutItemInput)
	OptFns    []func(opts *dynamodb.Options)
}
