package untyped

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/nguyengg/go-aws-commons/ddb-mapper/internal"
	mappertypes "github.com/nguyengg/go-aws-commons/ddb-mapper/types"
)

func (m *Mapper) Update(ctx context.Context, item any, optFns ...func(opts *UpdateOptions)) (*dynamodb.UpdateItemOutput, error) {
	var (
		opts  = internal.ApplyOpts(&UpdateOptions{}, optFns...)
		reset = internal.Chainable()
		expr  expression.Expression
	)

	c, err := Merge(ctx, m.Options, opts.Options)
	if err != nil {
		return nil, err
	}

	v, ptr, err := internal.IndirectValueIsStruct(item, true, m.StructType)
	if err != nil {
		return nil, err
	}

	if !opts.DisableOptimisticLocking && m.Version != nil {
		undo, cond := m.updateVersion(c, v, ptr)
		if opts.Condition.IsSet() {
			opts.Condition = opts.Condition.And(cond)
		} else {
			opts.Condition = cond
		}
		reset = reset.And(undo)
	}

	if !opts.DisableAutoGeneratedTimestamps && m.ModifiedTime != nil {
		reset = reset.And(m.updateTimestamps(v, time.Now(), false))
	}

	// instead of marshaling just the key, we'll marshal the entire item here so that we can use the AttributeValue
	// from the map's version and timestamps mappings to add to update expression.
	avM, err := m.encode(c, item)
	if err != nil {
		return nil, err
	}

	if !opts.DisableOptimisticLocking && m.Version != nil {
		if v, ok := avM[m.Version.AttrName]; ok {
			opts.Update = opts.Update.Set(expression.NameNoDotSplit(m.Version.AttrName), expression.Value(v))
		}
	}

	if !opts.DisableAutoGeneratedTimestamps && m.ModifiedTime != nil {
		if v, ok := avM[m.ModifiedTime.AttrName]; ok {
			opts.Update = opts.Update.Set(expression.NameNoDotSplit(m.ModifiedTime.AttrName), expression.Value(v))
		}
	}

	if opts.UpdateBehaviourIsSet {
		for n, av := range avM {
			attr, ok := m.Others[n]
			if !ok {
				// this will skip special attributes except for createdTime which is not set by Update.
				if m.CreatedTime != nil && n == m.CreatedTime.AttrName {
					attr = &m.CreatedTime.Attribute
				} else {
					continue
				}
			}

			if opts.UpdateBehaviour&mappertypes.UpdateBehaviourSkipZeroValues != 0 {
				if v.FieldByIndex(attr.Index).IsZero() {
					continue
				}
			}

			if _, isNull := av.(*types.AttributeValueMemberNULL); isNull {
				switch {
				case opts.UpdateBehaviour&mappertypes.UpdateBehaviourSkipNULLDataType != 0:
					continue
				case opts.UpdateBehaviour&mappertypes.UpdateBehaviourRemoveNULLDataType != 0:
					opts.Update = opts.Update.Remove(expression.NameNoDotSplit(n))
					continue
				}
			}

			opts.Update = opts.Update.Set(expression.NameNoDotSplit(n), expression.Value(av))
		}
	}

	b := expression.NewBuilder().WithUpdate(opts.Update)
	if opts.Condition.IsSet() {
		b = b.WithCondition(opts.Condition)
	}
	if expr, err = b.Build(); err != nil {
		if strings.Contains(err.Error(), "unset parameter: UpdateBuilder") {
			return nil, fmt.Errorf("build expressions error (did you forget to add an update clause?): %w", err)
		}

		return nil, fmt.Errorf("build expressions error: %w", err)
	}

	input := &dynamodb.UpdateItemInput{TableName: aws.String(m.TableName)}
	input.Key = m.copyKeys(avM)
	input.UpdateExpression = expr.Update()
	input.ConditionExpression = expr.Condition()
	input.ExpressionAttributeNames = expr.Names()
	input.ExpressionAttributeValues = expr.Values()

	if opts.TableName != nil {
		input.TableName = opts.TableName
	}
	if opts.ReturnAllNewValues && input.ReturnValues == "" {
		input.ReturnValues = types.ReturnValueAllNew
	}
	if opts.InputFn != nil {
		opts.InputFn(input)
	}

	updateItemOutput, err := c.Client.UpdateItem(ctx, input, opts.OptFns...)
	if err != nil {
		reset()
		return updateItemOutput, fmt.Errorf("dynamodb UpdateItem error: %w", err)
	}

	if opts.ReturnAllNewValues && input.ReturnValues == types.ReturnValueAllNew {
		if attributes := updateItemOutput.Attributes; len(attributes) != 0 {
			v.Set(reflect.Zero(m.StructType))

			if err = c.Decoder.Decode(&types.AttributeValueMemberM{Value: attributes}, ptr.Interface()); err != nil {
				return nil, fmt.Errorf("unmarshal ALL_NEW attributes to type %T error: %w", item, err)
			}
		}
	}

	return updateItemOutput, nil
}

func (m *Mapper) UpdateReturnAllNewValues(ctx context.Context, item any, optFns ...func(opts *UpdateOptions)) (*dynamodb.UpdateItemOutput, error) {
	return m.Update(ctx, item, append(optFns, func(opts *UpdateOptions) { opts.ReturnAllNewValues = true })...)
}

// UpdateOptions customises [Update].
//
// UpdateOptions can be modified either by changing the fields directly or via chaining With methods.
//
// The update methods (Set, Remove, Add, and Delete) all require a path argument that must be either a string (which
// will be wrapped using [expression.Name]), or an [expression.NameBuilder] so that you can use
// [expression.NameNoDotSplit] as the path. For update methods that require a value argument, the value will be wrapped
// with [expression.Value] if not already one so you can use [expression.ValueWithOptions] if the need arises.
type UpdateOptions struct {
	Options

	DisableOptimisticLocking       bool
	DisableAutoGeneratedTimestamps bool
	TableName                      *string
	UpdateBehaviour                mappertypes.UpdateBehaviour
	UpdateBehaviourIsSet           bool
	Update                         expression.UpdateBuilder
	UpdateIsSet                    bool
	Condition                      expression.ConditionBuilder
	ReturnAllNewValues             bool
	InputFn                        func(input *dynamodb.UpdateItemInput)
	OptFns                         []func(opts *dynamodb.Options)
}
